apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-kv-store
spec:
  provider:
    azurekv:
      authType: ServicePrincipal
      vaultUrl: https://k8s-homelab-production.vault.azure.net
      tenantId: 6ddecc48-41b1-48de-bfde-2efd29fae9c7
      authSecretRef:
        clientId:
          name: azure-creds
          key: ClientID
          namespace: external-secrets
        clientSecret:
          name: azure-creds
          key: ClientSecret
          namespace: external-secrets
