apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi-retain
  annotations:
provisioner: csi.san.synology.com
parameters:
  dsm: "192.168.120.186"
  location: "/volume1"
  protocol: iscsi
  csi.storage.k8s.io/fstype: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
