---
creation_rules:
  - path_regex: clusters/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1ft4dldx5zezaajkju2gsaugvtqqhvughw3hw29ekl7qvdcukfq3spcfntq"
  - path_regex: databases/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1ft4dldx5zezaajkju2gsaugvtqqhvughw3hw29ekl7qvdcukfq3spcfntq"
  - path_regex: infrastructure/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1ft4dldx5zezaajkju2gsaugvtqqhvughw3hw29ekl7qvdcukfq3spcfntq"
  - path_regex: monitoring/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1ft4dldx5zezaajkju2gsaugvtqqhvughw3hw29ekl7qvdcukfq3spcfntq"
  - path_regex: utils/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1ft4dldx5zezaajkju2gsaugvtqqhvughw3hw29ekl7qvdcukfq3spcfntq"
  # For stdin operations (e.g., piping)
  - path_regex: /dev/stdin
    key_groups:
      - age:
          - "age1ft4dldx5zezaajkju2gsaugvtqqhvughw3hw29ekl7qvdcukfq3spcfntq"