apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sops
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: sops
      version: "1.*"
      sourceRef:
        kind: HelmRepository
        name: sops
        namespace: flux-system
      interval: 12h
  values:
    installCRDs: true
