apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 1h
  chart:
    spec:
      chart: external-dns
      version: "v1.15.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns

  valuesFrom:
    - kind: ConfigMap
      name: external-dns-values
