---
apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: "{prefix}-db-production-v0"
  namespace: "{prefix}"
spec:
  backup:
    barmanObjectStore:
      azureCredentials:
        storageAccount:
          key: "{prefix}-storage-account-name"
          name: azure-creds
        storageSasToken:
          key: "{prefix}-blob-sas"
          name: azure-creds
      data:
        compression: gzip
      destinationPath: "https://{storage_account}.blob.core.windows.net/{prefix}"
      wal:
        compression: gzip
    retentionPolicy: 14d
  bootstrap:
    initdb:
      database: "{prefix}"
      owner: "{prefix}"
      secret:
        name: "{prefix}-db-creds"
  description: "Postgres cluster for the {prefix} application"
  imageName: quay.io/enterprisedb/postgresql:16.1
  inheritedMetadata:
    labels:
      app: "{prefix}-database"
      policy-type: database
  instances: 3
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      memory: 100Mi
  storage:
    size: 1Gi
---
apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: ScheduledBackup
metadata:
  name: "{prefix}-db-production"
  namespace: "{prefix}"
spec:
  backupOwnerReference: cluster
  cluster:
    name: "{prefix}-db-production-v0"
  immediate: true
  schedule: "0 0 3 * *"
