apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
  namespace: skool
spec:
  provider: azure
  parameters:
    keyvaultName: k8s-homelab-production

    objects: |
      array:
        - |
          objectName: skool-connection-string
          objectType: secret
        - |
          objectName: skool-storage-account-name
          objectType: secret
        - |
          objectName: skool-blob-sas
          objectType: secret
        - |
          objectName: skool-db-username
          objectType: secret
        - |
          objectName: skool-db-password
          objectType: secret

    tenantId: 6ddecc48-41b1-48de-bfde-2efd29fae9c7

  secretObjects:
    - data:
        - key: skool-connection-string
          objectName: skool-connection-string
        - key: skool-storage-account-name
          objectName: skool-storage-account-name
        - key: skool-blob-sas
          objectName: skool-blob-sas
      secretName: azure-creds
      type: Opaque

    - data:
        - key: username
          objectName: skool-db-username
        - key: password
          objectName: skool-db-password
      secretName: skool-db-creds
      type: kubernetes.io/basic-auth
