apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cloudflare-tunnel
  namespace: linkding
spec:
  selector:
    matchLabels:
      app: cloudflared
  podMetricsEndpoints:
    - port: http-metrics
