apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: ingress-pool
  namespace: kube-system
spec:
  blocks:
    - start: "192.168.100.192"
      stop: "192.168.100.195"

  serviceSelector:
    matchLabels:
      cilium.io/ingress: "true"
