apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: ingress-policy
  namespace: kube-system
spec:
  serviceSelector:
    matchLabels:
      cilium.io/ingress: "true"

  # IMPORTANT: if externalIPss is desired, externalIPs.enabled=true must be set in values.yaml
  # externalIPs: true
  loadBalancerIPs: true
