apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: renovate-container-env
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-store
    kind: ClusterSecretStore
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: renovate-token
