apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-creds
    namespace: n8n
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:WlXa,iv:OLYmK3yIJ/8SdbsSVWrXlGwn052aMndbwq1aWqEqRIU=,tag:ccwt3oJB3zv3GIauhohvtg==,type:str]
    password: ENC[AES256_GCM,data:3ShKKKv5jDI=,iv:0U/SH23BbF/O2gfWqprJRV0PP0bmfv2gSk2st6vrQd0=,tag:YY3sPv4+IWxtM1lC9hycng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ft4dldx5zezaajkju2gsaugvtqqhvughw3hw29ekl7qvdcukfq3spcfntq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweUlFL0plQ1NRaEJpK0Jt
            Q2hNQ21HNEFEWGdqQm9OQWdid0J4TlptWlg4CmpSb2d0SUpJNlRSSEsxM1B5SVpx
            MGJlUlBMUklTNVowNzliYXBYcmN2MXMKLS0tIDFraEFEajRiNWVRUnQ0cTJ5bjNh
            MUEzZ3IwbTBJVGJUaitOYURwS2pGNTgKI0n0IwxRt7Tcx81It/bftzFCSlXgzPsN
            W+lycWQxnYlandU8K/s8KOp/60zPpmoFwri0IfAMqVOxsnpaMSnGQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-22T21:23:09Z"
    mac: ENC[AES256_GCM,data:ymH2OgFhztuighvWOY1WlnbtSMpgxPph+skaUj/kfY2viv86kO+3J6uefgEkEnAHIXrtbhR11DThe58Qh15xOQXBIfLrvQwJI+rh+k+rrT4bYsq0aPl+AUOdgtOEe5U2N1NG50ZlzlkaKutYpmwkdvZ2soVLjvWXWLXhCnQlUbs=,iv:k3rorH5/C7YEj/SmlPsCfN3idjHTWE4M1yGUIqqXxQ8=,tag:1EqqEOYC28sNBax3hsg87g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
