apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-creds
    namespace: n8n
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:6LFB,iv:MRigw+TvsukTivGz24646PyVpU+gfuRVTv6AI56c9Z0=,tag:Nk0KW4NHiJsDKGuXeWOfiQ==,type:str]
    password: ENC[AES256_GCM,data:7rLh4jfGQdw=,iv:Zaei7/3TPK2xN3flnVfiFhsSs8l1aywrysjYDfBRyrY=,tag:ypMeX5KVGSi+ZF+kc+8YDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13ekfyr0maz899nwum2j0jjjsxdamptqc706dd6gjpdpmen7rg4ms8u9n7x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3WlpKNzN4SkZZRXRxdEtw
            ZDlPbHpGSUh3Q1FtZ2dzVTRSVlAwZTFKM1FnClNMVnNPN25Kb29hMXJCQmhCbUJX
            RXlUT1hxeWpaaEh2dTF1a2tWUWZiUFkKLS0tIHFJZk8rQ2FiQjZjcHJycVlWWG9L
            dlJJUUxZUktxcCtpWGQ2Vng5Mnp2UzgKAm11ApIvMjTORKIIEe5eRorc1Js+WJaJ
            2vhHWctLNexpocX20tvMV5g23pjxldtWioBlfoh7Ahi440SYIm8ZRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-22T19:54:30Z"
    mac: ENC[AES256_GCM,data:IilQd9MKFRDQIVYge07xkkHQnLiEXl9sSuQE5SSpixv7NdymKzI8DLl3IyYhiBkgynMOnWztAIYYDNGiPe7MIAq6vdr9Wu/9j4HVjvOraCs+DIr0ulsiy/WSkHgqlkuDsKzkxi3nln+JmtBSxzlF/O1TrToWO0OBjzc/0G3E+Ls=,iv:bsga1GxQHknSzRwtdb14L9LM2M97504oZcxDgxNFOso=,tag:f66IlZSeV4gbTmZo78JaeQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
